//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosted_at
    {
        public int id { get; set; }
        public int guest_id { get; set; }
        public int occupied_room_id { get; set; }
    
        public virtual guest guest { get; set; }
        public virtual occupied_room occupied_room { get; set; }
    }
}
