//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<guest> guest { get; set; }
        public virtual DbSet<hosted_at> hosted_at { get; set; }
        public virtual DbSet<occupied_room> occupied_room { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<room_type> room_type { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
