//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class occupied_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public occupied_room()
        {
            this.hosted_at = new HashSet<hosted_at>();
        }
    
        public int id { get; set; }
        public System.TimeSpan check_in { get; set; }
        public System.TimeSpan check_out { get; set; }
        public int room_id { get; set; }
        public int reservation_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hosted_at> hosted_at { get; set; }
        public virtual reservation reservation { get; set; }
        public virtual room room { get; set; }
    }
}
